tutores/urls.py
from django.conf.urls import url
from . import views


app_name = 'tutores'
urlpatterns = [
    #/tutor/
    url(r'^$',views.IndexView.as_view(), name='index'), #name

    #/tutor/71
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detalle'),
]

tutorial/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tutores/', include('tutores.urls'))
]

tutores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Tutor(models.Model):
    nombre = models.CharField(max_length=250, default="")
    fechaDeNacimiento = models.DateField()
    direccion = models.CharField(max_length=500)
    ciudad = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre + " | " + self.ciudad

class Curso(models.Model):
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE,default=1)
    nombre = models.CharField(max_length=250)
    descripcion = models.CharField(max_length=1000)
    fechaDeInicio = models.DateField()
    terminado = models.BooleanField(default=False)


    def __str__(self):
        return self.nombre

tutores/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views import generic
from .models import Tutor

class IndexView(generic.ListView):
    template_name='tutores/index.html'

    def get_queryset(self):
        return Tutor.objects.all()

class DetailView(generic.DetailView):
    model = Tutor
    template_name="tutores/detalle.html"

tutores/templates/tutores/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <title> {% block titulo %} {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'tutores/stylesheet.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'tutores:index' %}">CEPCQ</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                <li class="">
                    <a href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Tutores </a>

                </li>

                <li class="">
                    <a href="#"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Cursos </a>

                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value=""/>
                    <button type="submit" class="btn btn-default">Buscar</button>
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                     <a href="#"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Añadir tutor</a>
                 </li>

                <li class="">
                    <a href="#"> <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Salir </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

tutores/templates/tutores/detalle.html
{% extends 'tutores/base.html' %}
{% block titulo %} Cursos {% endblock %}

{% block body %}
    <img src="/tutores/templates/tutores/capacitado.png">
    <h1> {{ tutor.nombre }}</h1>
    <h3> {{ tutor.ciudad }}</h3>


    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

        {% for curso in tutor.curso_set.all %}
            <input type="radio" id="curso{{ forloop.counter }}" name="curso" value="{{ curso.id }}" />
            <label for="curso{{ forloop.counter }}">
                {{ curso.nombre }}
                {%  if curso.terminado %}
                    <img src="https://d1whdhnvermmdv.cloudfront.net/assets/check_16.png"/>
                {% endif %}
            </label><br>
        {% endfor %}
{% endblock %}

tutores/templates/tutores/index.html
{% extends 'tutores/base.html' %}
{% block titulo %} Tutores {% endblock %}
{% block body %}

        {%  if object_list %}
            <h3> Aquí están todos tus tutores</h3>

        {% else %}
            <h3> No tienes ningún Tutor, puñetas.</h3>
        {% endif %}
        <ul>
            {% for tutor in object_list%}
            <li> <a href="{% url 'tutores:detalle' tutor.id %}"> {{ tutor.nombre }} </a></li>
            {% endfor %}
        </ul>
{% endblock %}